# Generated by Django 4.0.8 on 2022-11-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('data_feed', models.TextField(blank=True, null=True)),
                ('series', models.ForeignKey(blank=True, help_text='Which series it belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='series.seriespage')),
                ('team_1', models.ForeignKey(blank=True, help_text='Team 1 of the match.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.teamspage')),
                ('team_2', models.ForeignKey(blank=True, help_text='Team 2 of the match.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.teamspage')),
            ],
            options={
                'verbose_name_plural': 'Match',
            },
        ),
    ]
