# Generated by Django 4.0.8 on 2022-11-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_stadium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AddField(
            model_name='match',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.stadium'),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Started'), (1, 'In Play'), (2, 'Finished'), (3, 'Abandoned')], default=0),
        ),
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.country')),
            ],
        ),
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Which city it belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='series.city'),
        ),
    ]
