# Generated by Django 4.0.8 on 2022-11-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_alter_match_options_match_remarks_match_stadium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
