# Generated by Django 4.0.8 on 2022-11-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_stadium_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
