# Generated by Django 4.0.8 on 2022-11-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_match_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
