# Generated by Django 4.0.8 on 2022-11-18 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_alter_match_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AddField(
            model_name='stadium',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Which country it belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='series.country'),
        ),
        migrations.AlterField(
            model_name='match',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
